// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guyfffakmajvaqbrtwpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eWZmZmFrbWFqdmFxYnJ0d3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTEzOTgsImV4cCI6MjA2OTQ2NzM5OH0.JCHMn0s5UxSHfEq5TCSPFhstR5TUKwGLHYARgPFoN2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});